[package]
name = "parse_rc_ibus"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "A simple parser for FlySky IBUS"
repository = "https://github.com/sergeant-savage/parse_rc_ibus"

[dependencies]
